language: perl
perl:
  - "5.18"
before_install:
  - sudo apt-get install --assume-yes geoip-database geoip-bin libgeoip-dev
  - sudo mkdir -p /usr/local/share/GeoIP
  - sudo mkdir -p /usr/share/GeoIP
  - wget -N http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
  - gunzip GeoLiteCity.dat.gz
  - sudo cp GeoLiteCity.dat /usr/local/share/GeoIP/
  - sudo cp GeoLiteCity.dat /usr/share/GeoIP/
  - mkdir -p var/log
install:
  - cpanm --quiet --installdeps --notest .
script:
  - "WF_STREAM=live WF_PATH=`pwd` prove -lrv t"
notifications:
  email:
    recipients:
      - olaf@wundersolutions.com
    on_success: always
    on_failure: always
