language: perl
perl:
  - "5.16"
  - "5.14"
before_install:
  - sudo apt-get install --assume-yes geoip-database geoip-bin libgeoip-dev
install:
  - cpanm --verbose --installdeps --notest .
script:
  - "WF_STREAM=live WF_PATH=`pwd` prove -lrv t"
notifications:
  email:
    recipients:
      - olaf@wundersolutions.com
    on_success: always
    on_failure: always
