requires 'Business::PayPal::API';
requires 'CGI::Application::Plugin::AnyTemplate';
requires 'CGI::Application::Plugin::FillInForm';
requires 'CGI::Application::Plugin::Forward';
requires 'CGI::Application::Plugin::HTDot';
requires 'CGI::Application::Plugin::Redirect';
requires 'CGI::Application::Plugin::Stash';
requires 'CGI::Application::Plugin::ValidateRM';
requires 'Check::ISA';
requires 'Config::General';
requires 'Data::Dump';
requires 'Data::Printer::Filter::JSON';
requires 'Data::Printer::Filter::URI';
requires 'Data::Validate::URI';
requires 'DateTime';
requires 'DateTime::Format::ISO8601';
requires 'DateTime::Format::Mail';
requires 'DateTime::Format::MySQL';
requires 'DBD::SQLite'; # Locale::Object
requires 'DBIx::Class';
requires 'Devel::SimpleTrace';
requires 'Email::Sender::Simple', '>=', '1.300031';
requires 'Email::Valid';
requires 'File::MimeInfo::Magic';
requires 'File::Slurp';
requires 'File::Tools';
requires 'Find::Lib';
requires 'Geo::Coder::GoogleMaps';
requires 'Geo::IP', '<= 1.40';
requires 'Hash::Merge';
requires 'Locale::SubCountry';
requires 'Log::Log4perl';
requires 'Math::Round';
requires 'MIME::Lite';
requires 'Modern::Perl';
requires 'MooseX::Getopt';
requires 'MooseX::NonMoose';
requires 'MooseX::Params::Validate';
requires 'MooseX::StrictConstructor';
requires 'Net::Twitter';
requires 'Params::Validate', '>=', '1.29';
requires 'Params::Validate', '1.29';
requires 'Scalar::Util';
requires 'Scalar::Util::Numeric';
requires 'String::Random';
requires 'Test::Perl::Critic';
requires 'Text::Autoformat';
requires 'WWW::Mechanize';
requires 'XML::Simple';
